# Generated by Django 4.2.3 on 2023-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee_pictures/'),
        ),
    ]
